### PR TITLE
[Minor] lua_scanner - spamassassin - another try to match all spamd r…

### LINKED ISSUE #4088: [BUG] lua_tcp_push_data: callback call failed: /usr/share/rspamd/lualib/lua_scanners/spamassassin.lua:173: attempt to compare number with nil
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd sometimes logs an error after calling external_service spamassassin. It seems to still work though.

### Steps to Reproduce

1. Configure rspamd to use external_service spamassassin
2. Produce enough traffic / scans
3. Observe sporadic error messages

`lua_tcp_push_data: callback call failed: /usr/share/rspamd/lualib/lua_scanners/spamassassin.lua:173: attempt to compare number with nil`

**Expected behavior**
No error shows up

### Versions
rspamd --version: 3.1
Running debian 10 using rspamd repository.

This might be related to https://github.com/rspamd/rspamd/issues/3141

### PR DESCRIPTION
**Pull request by c-rosenberg**
…eturns

fix #4088

### CODE REVIEW

File: lualib/lua_scanners/spamassassin.lua [hunk 1]
```diff
@@ -147,37 +147,36 @@ local function spamassassin_check(task, content, digest, rule)
...
+
         if tonumber(spam_score) > 0 and #symbols > 0 and symbols ~= "none" then
 
           if rule.extended == false then
             common.yield_result(task, rule, symbols, spam_score)
             common.save_cache(task, digest, rule, symbols, spam_score)
           else
-            local symbols_table = {}
-            symbols_table = lua_util.str_split(symbols, ",")
+            local symbols_table = lua_util.str_split(symbols, ",")
```
Comment (vstakhov) [inline lualib/lua_scanners/spamassassin.lua:179]: 👍

**Review by vstakhov — APPROVED** [review]
